
###
GET http://localhost:3000/organization/public

###
DELETE http://localhost:3000/categories/5

###
POST http://localhost:3000/users/auth/register
Content-Type: application/json

{
    "firstName":"Pablo",
	"lastName":"Lnombre",
	"email":"amzon@hotmail.com",
	"password":"123456"
}

### GET USERS 
GET  http://localhost:3000/users/

### GET ROLES
GET  http://localhost:3000/roles/