### GET USERS 
GET  http://localhost:3000/users/

### GET ROLES
GET  http://localhost:3000/roles/


### GET ROLE BY ID 
GET  http://localhost:3000/roles/1

### GET CATEGORIES
GET  http://localhost:3000/categories

### GET CATEGORY by ID
GET  http://localhost:3000/categories/3



### DELETE CATEGORY by ID

DELETE  http://localhost:3000/categories/2